### ISSUE TITLE
Unable to perform a handshake

### ISSUE THREAD

**Issue by DVSoftware** [githoniel/node-https-hsm#1]
Hi, 
I know it's been a long time since you released this package, but I can't figure out why the sever closes a connection with ECONNRESET as soon as i write the handshake data. 
I'm trying to authenticate to a website that requires using a certificate and private key on a smart card, so I exported the certificate and I'm using the signing capabilities of the card, but it doesn't get to the point where it's called.

I don't know which details would be helpful for debugging this, but you should be able to try with 'api.sandbox.suf.purs.gov.rs:443' even without certificates (because it bails out before trying to use them).

**Comment by githoniel** [comment]
@DVSoftware  sorry I could not help, but you may debug like below

1. use [wireshark](https://www.wireshark.org/) to capture handshake packets
2. It will be much easier if you have success handshake packets to compare with
3. check handshake packets by reading [rfc5246](https://datatracker.ietf.org/doc/html/rfc5246)

Notice this package only support  twp cipher suites `TLS_RSA_WITH_AES_128_CBC_SHA256 ` and `TLS_RSA_WITH_AES_256_CBC_SHA256 `, although most servers support them.

**Comment by DVSoftware** [comment]
So i managed to progress further with this, the IIS was rejecting the connection because it was missing the SNI packet. 
However, now when i send the certificate I get the same result.

I see that server supports the cipher:
```
PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: CPORT    STATE SERVICE
```

The problem is, however, that i don't see it in the PKCS11 library i use: https://github.com/PeculiarVentures/graphene/blob/master/src/mech_enum.ts

Mechanisms supported by the card
```
SHA_1                      +/-/-/-/-/-/-
SHA224                     +/-/-/-/-/-/-
SHA256                     +/-/-/-/-/-/-
SHA384                     +/-/-/-/-/-/-
SHA512                     +/-/-/-/-/-/-
MD5                        +/-/-/-/-/-/-
RIPEMD160                  +/-/-/-/-/-/-
GOSTR3411                  +/-/-/-/-/-/-
RSA_PKCS                   -/+/+/-/+/-/-
SHA1_RSA_PKCS              -/+/+/-/-/-/-
SHA224_RSA_PKCS            -/+/+/-/-/-/-
SHA256_RSA_PKCS            -/+/+/-/-/-/-
SHA384_RSA_PKCS            -/+/+/-/-/-/-
SHA512_RSA_PKCS            -/+/+/-/-/-/-
MD5_RSA_PKCS               -/+/+/-/-/-/-
RIPEMD160_RSA_PKCS         -/+/+/-/-/-/-
RSA_PKCS_KEY_PAIR_GEN      -/-/-/-/-/-/-
```

Maybe i got it wrong, and it's not the same thing? Which mechanism am i supposed to pick when signing the message?

**Comment by githoniel** [comment]
I think `RSA_PKCS` is what you need. I assume you need to sign data by Card  in `rsaSign` callback

**Comment by DVSoftware** [comment]
I tried that, remote server closes the connection as soon as the certificate is sent. Not sure how to debug this any further :(

**Comment by DVSoftware** [comment]
I just realized i commented out some code that checks if the certificate needs to be sent.
The server doesn't get to the point of sending a Certificate Request.
It actually disconnects after an Alert (100 - no_renegotiation) is sent, because it sends another handshake message.
I suspect this is the problem, but i'm not sure how to resolve it.

![Screenshot 2021-12-08 at 15 49 23](https://user-images.githubusercontent.com/429515/145229200-4f1db232-5b6f-46ad-ba2d-28aed68b37ff.png)

**Comment by DVSoftware** [comment]
Judging from the wireshark dump from another application that successfully performs this request, it seems that server wants to use Diffie-Hellman, which seems like a no go here :(

**Comment by DVSoftware** [comment]
Implemented a small service in Java that does this. Until some better times come.
